package geometricapp;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * Main JFrame, main windows that holds the most tools.
 * 
 * @author Bruno García Trípoli
 */
public class JFrameApp extends javax.swing.JFrame {

    /**
     * Creates new form JFrameApp
     */
    public JFrameApp() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnl_options = new javax.swing.JPanel();
        jslider_edges = new javax.swing.JSlider();
        jlbl_out_edges = new javax.swing.JLabel();
        jslider_size = new javax.swing.JSlider();
        jlbl_out_size = new javax.swing.JLabel();
        jpnl_out_info_area = new javax.swing.JPanel();
        jlbl_out_info_offset_angle = new javax.swing.JLabel();
        jlbl_out_info_area = new javax.swing.JLabel();
        jlbl_info_edge_length = new javax.swing.JLabel();
        jlbl_out_edge_length = new javax.swing.JLabel();
        jlbl_out_info_shape_name = new javax.swing.JLabel();
        jbtn_reset_angle = new javax.swing.JButton();
        jpnl_canvas = new javax.swing.JPanel();
        jtbtn_magic = new javax.swing.JToggleButton();
        jmenu_bar = new javax.swing.JMenuBar();
        jmenu_edit = new javax.swing.JMenu();
        jmenu_edit_reset = new javax.swing.JMenuItem();
        jmenu_edit_scale = new javax.swing.JMenuItem();
        jmenu_view = new javax.swing.JMenu();
        jmenu_view_shcenter = new javax.swing.JCheckBoxMenuItem();
        jmenu_view_shcircle = new javax.swing.JCheckBoxMenuItem();
        jmenu_show_shlines = new javax.swing.JCheckBoxMenuItem();
        jmenu_help = new javax.swing.JMenu();
        jmenu_help_about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geometric App");
        setBackground(new java.awt.Color(68, 68, 68));
        setName("Geometric App"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jpnl_options.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jlbl_final_edges.setLabelFor(jslider_edges);
        jlbl_final_edges.setText("Edges Count: ");
        jlbl_final_edges.setToolTipText("");

        jslider_edges.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jslider_edges.setMaximum(8);
        jslider_edges.setMinimum(3);
        jslider_edges.setMinorTickSpacing(1);
        jslider_edges.setPaintTicks(true);
        jslider_edges.setSnapToTicks(true);
        jslider_edges.setValue(3);

        jlbl_out_edges.setLabelFor(jslider_edges);
        jlbl_out_edges.setText("<number>");

        jlbl_final_size.setLabelFor(jslider_size);
        jlbl_final_size.setText("Size:");
        jlbl_final_size.setToolTipText("");

        jslider_size.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jslider_size.setMinorTickSpacing(10);
        jslider_size.setPaintTicks(true);
        jslider_size.setToolTipText("");
        jslider_size.setValue(20);

        jlbl_out_size.setLabelFor(jslider_size);
        jlbl_out_size.setText("<percentage>");

        javax.swing.GroupLayout jpnl_optionsLayout = new javax.swing.GroupLayout(jpnl_options);
        jpnl_options.setLayout(jpnl_optionsLayout);
        jpnl_optionsLayout.setHorizontalGroup(
            jpnl_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_optionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnl_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnl_optionsLayout.createSequentialGroup()
                        .addComponent(jlbl_final_edges)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbl_out_edges))
                    .addComponent(jslider_edges, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnl_optionsLayout.createSequentialGroup()
                        .addComponent(jlbl_final_size)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbl_out_size))
                    .addComponent(jslider_size, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jpnl_optionsLayout.setVerticalGroup(
            jpnl_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_optionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnl_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_final_edges)
                    .addComponent(jlbl_out_edges))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jslider_edges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnl_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_final_size)
                    .addComponent(jlbl_out_size))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jslider_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnl_out_info_area.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jlbl_final_info.setText("Info");

        jlbl_final_info_angle.setText("Offset Angle: ");

        jlbl_out_info_offset_angle.setText("<degrees>");

        jlbl_final_info_area.setText("Area: ");

        jlbl_out_info_area.setText("<number>");

        jlbl_info_edge_length.setText("Edge Length: ");

        jlbl_out_edge_length.setText("<number>");

        jlbl_final_info_shape.setText("Shape: ");

        jlbl_out_info_shape_name.setText("<name>");

        javax.swing.GroupLayout jpnl_out_info_areaLayout = new javax.swing.GroupLayout(jpnl_out_info_area);
        jpnl_out_info_area.setLayout(jpnl_out_info_areaLayout);
        jpnl_out_info_areaLayout.setHorizontalGroup(
            jpnl_out_info_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_out_info_areaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnl_out_info_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl_final_info)
                    .addGroup(jpnl_out_info_areaLayout.createSequentialGroup()
                        .addGroup(jpnl_out_info_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_info_edge_length)
                            .addComponent(jlbl_final_info_area)
                            .addComponent(jlbl_final_info_shape)
                            .addComponent(jlbl_final_info_angle))
                        .addGap(23, 23, 23)
                        .addGroup(jpnl_out_info_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_out_info_offset_angle)
                            .addComponent(jlbl_out_info_shape_name)
                            .addComponent(jlbl_out_info_area)
                            .addComponent(jlbl_out_edge_length))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jpnl_out_info_areaLayout.setVerticalGroup(
            jpnl_out_info_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_out_info_areaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbl_final_info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnl_out_info_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_final_info_shape)
                    .addComponent(jlbl_out_info_shape_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnl_out_info_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_info_edge_length)
                    .addComponent(jlbl_out_edge_length))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnl_out_info_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_final_info_area)
                    .addComponent(jlbl_out_info_area))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnl_out_info_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_final_info_angle)
                    .addComponent(jlbl_out_info_offset_angle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtn_reset_angle.setText("Reset angle offset");
        jbtn_reset_angle.setToolTipText("");

        jpnl_canvas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jpnl_canvasLayout = new javax.swing.GroupLayout(jpnl_canvas);
        jpnl_canvas.setLayout(jpnl_canvasLayout);
        jpnl_canvasLayout.setHorizontalGroup(
            jpnl_canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
        );
        jpnl_canvasLayout.setVerticalGroup(
            jpnl_canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        jtbtn_magic.setFont(new java.awt.Font("SansSerif", 0, 67)); // NOI18N
        jtbtn_magic.setText("✡");
        jtbtn_magic.setEnabled(false);

        jmenu_edit.setText("Edit");
        jmenu_edit.setToolTipText("");

        jmenu_edit_reset.setText("Reset Rotation");
        jmenu_edit_reset.setToolTipText("");
        jmenu_edit.add(jmenu_edit_reset);

        jmenu_edit_scale.setText("Reset Scale");
        jmenu_edit.add(jmenu_edit_scale);

        jmenu_bar.add(jmenu_edit);

        jmenu_view.setText("View");
        jmenu_view.setToolTipText("");

        jmenu_view_shcenter.setSelected(true);
        jmenu_view_shcenter.setText("Show center");
        jmenu_view.add(jmenu_view_shcenter);

        jmenu_view_shcircle.setText("Show Circle");
        jmenu_view.add(jmenu_view_shcircle);

        jmenu_show_shlines.setText("Show Help Lines");
        jmenu_view.add(jmenu_show_shlines);

        jmenu_bar.add(jmenu_view);

        jmenu_help.setText("Help");
        jmenu_help.setToolTipText("");

        jmenu_help_about.setText("About");
        jmenu_help.add(jmenu_help_about);

        jmenu_bar.add(jmenu_help);

        setJMenuBar(jmenu_bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnl_canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpnl_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpnl_out_info_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_reset_angle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtbtn_magic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_reset_angle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtbtn_magic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jpnl_out_info_area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnl_options, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnl_canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatDarkLaf look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If FlatDarkLaf (external look and feel) is not available, stay with the default look and feel.
         * For details see https://www.formdev.com/flatlaf/ 
         */        
        com.formdev.flatlaf.FlatDarkLaf.setup();
        try {
            UIManager.setLookAndFeel( new com.formdev.flatlaf.FlatDarkLaf() );
        } catch( Exception ex ) {
             java.util.logging.Logger.getLogger(JFrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_reset_angle;
    private final javax.swing.JLabel jlbl_final_edges = new javax.swing.JLabel();
    private final javax.swing.JLabel jlbl_final_info = new javax.swing.JLabel();
    private final javax.swing.JLabel jlbl_final_info_angle = new javax.swing.JLabel();
    private final javax.swing.JLabel jlbl_final_info_area = new javax.swing.JLabel();
    private final javax.swing.JLabel jlbl_final_info_shape = new javax.swing.JLabel();
    private final javax.swing.JLabel jlbl_final_size = new javax.swing.JLabel();
    private javax.swing.JLabel jlbl_info_edge_length;
    private javax.swing.JLabel jlbl_out_edge_length;
    private javax.swing.JLabel jlbl_out_edges;
    private javax.swing.JLabel jlbl_out_info_area;
    private javax.swing.JLabel jlbl_out_info_offset_angle;
    private javax.swing.JLabel jlbl_out_info_shape_name;
    private javax.swing.JLabel jlbl_out_size;
    private javax.swing.JMenuBar jmenu_bar;
    private javax.swing.JMenu jmenu_edit;
    private javax.swing.JMenuItem jmenu_edit_reset;
    private javax.swing.JMenuItem jmenu_edit_scale;
    private javax.swing.JMenu jmenu_help;
    private javax.swing.JMenuItem jmenu_help_about;
    private javax.swing.JCheckBoxMenuItem jmenu_show_shlines;
    private javax.swing.JMenu jmenu_view;
    private javax.swing.JCheckBoxMenuItem jmenu_view_shcenter;
    private javax.swing.JCheckBoxMenuItem jmenu_view_shcircle;
    private javax.swing.JPanel jpnl_canvas;
    private javax.swing.JPanel jpnl_options;
    private javax.swing.JPanel jpnl_out_info_area;
    private javax.swing.JSlider jslider_edges;
    private javax.swing.JSlider jslider_size;
    private javax.swing.JToggleButton jtbtn_magic;
    // End of variables declaration//GEN-END:variables
}
